/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package corpoagrima.corpoagrima.gui.regventa;
import java.sql.Connection;
import java.sql.ResultSet;
/**
 *
 * @author User
 */
public class EditarRegFactura extends javax.swing.JFrame {
    private final Connection conexion;
    private final ResultSet credenciales;
    /**
     * Creates new form EditarRegFactura
     * @param conexion
     * @param credenciales
     */
    public EditarRegFactura(Connection conexion, ResultSet credenciales) {
        this.conexion = conexion;
        this.credenciales = credenciales;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        encabezadoJPanel = new javax.swing.JPanel();
        puestoJLabel = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        Apellido_Label = new javax.swing.JLabel();
        Nombre_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NoFactura_TextField1 = new javax.swing.JTextField();
        Nombre_jLabel2 = new javax.swing.JLabel();
        Apellido_TextField = new javax.swing.JTextField();
        Apellido_Label1 = new javax.swing.JLabel();
        Direccion_TextField = new javax.swing.JTextField();
        Direccion_Label = new javax.swing.JLabel();
        Direccion_TextField1 = new javax.swing.JTextField();
        Empleado_label = new javax.swing.JLabel();
        Empleado_TextField = new javax.swing.JTextField();
        Fecha_label = new javax.swing.JLabel();
        Fecha_TextField = new javax.swing.JTextField();
        Destacado_label = new javax.swing.JLabel();
        Destacado_checkBox = new javax.swing.JCheckBox();
        Direccion_Label1 = new javax.swing.JLabel();
        Detalles_TextField = new javax.swing.JTextField();
        Consumidor_CheckBox = new javax.swing.JCheckBox();
        NIT_CheckBox = new javax.swing.JCheckBox();
        Destacado_label1 = new javax.swing.JLabel();
        Destacado_checkBox1 = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos_table = new javax.swing.JTable();
        Agregar_button = new javax.swing.JButton();
        Eliminar_button = new javax.swing.JButton();
        Destacado_label2 = new javax.swing.JLabel();
        Efectivo_TextField = new javax.swing.JTextField();
        Destacado_label3 = new javax.swing.JLabel();
        Cambio_TextField = new javax.swing.JTextField();
        Destacado_label4 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();
        Guardar_Button = new javax.swing.JButton();
        Limpiar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encabezadoJPanel.setBackground(new java.awt.Color(34, 85, 34));

        puestoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        puestoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        puestoJLabel.setText("Editar Registro Factura");

        back_Button.setBackground(new java.awt.Color(34, 85, 34));
        back_Button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        back_Button.setForeground(new java.awt.Color(255, 255, 255));
        back_Button.setText("←");
        back_Button.setBorderPainted(false);
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout encabezadoJPanelLayout = new javax.swing.GroupLayout(encabezadoJPanel);
        encabezadoJPanel.setLayout(encabezadoJPanelLayout);
        encabezadoJPanelLayout.setHorizontalGroup(
            encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoJPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(back_Button)
                .addGap(159, 159, 159)
                .addComponent(puestoJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        encabezadoJPanelLayout.setVerticalGroup(
            encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encabezadoJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Apellido_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido_Label.setText("Apellido");

        Nombre_TextField.setToolTipText("Número de factura");
        Nombre_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_TextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("No. Factura");

        NoFactura_TextField1.setToolTipText("Número de factura");
        NoFactura_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoFactura_TextField1ActionPerformed(evt);
            }
        });

        Nombre_jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre_jLabel2.setText("Nombre");

        Apellido_TextField.setToolTipText("Número de factura");
        Apellido_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido_TextFieldActionPerformed(evt);
            }
        });

        Apellido_Label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido_Label1.setText("Dirección");

        Direccion_TextField.setToolTipText("Número de factura");
        Direccion_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion_TextFieldActionPerformed(evt);
            }
        });

        Direccion_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Direccion_Label.setText("Nit");

        Direccion_TextField1.setToolTipText("Número de factura");
        Direccion_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion_TextField1ActionPerformed(evt);
            }
        });

        Empleado_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Empleado_label.setText("Empleado");

        Empleado_TextField.setToolTipText("Número de factura");
        Empleado_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empleado_TextFieldActionPerformed(evt);
            }
        });

        Fecha_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fecha_label.setText("Fecha");

        Fecha_TextField.setToolTipText("Número de factura");
        Fecha_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_TextFieldActionPerformed(evt);
            }
        });

        Destacado_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label.setText("Destacado");

        Destacado_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destacado_checkBoxActionPerformed(evt);
            }
        });

        Direccion_Label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Direccion_Label1.setText("Detalle");

        Detalles_TextField.setToolTipText("Número de factura");
        Detalles_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detalles_TextFieldActionPerformed(evt);
            }
        });

        Consumidor_CheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Consumidor_CheckBox.setText("Consumidor Final");

        NIT_CheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIT_CheckBox.setText("NIT");

        Destacado_label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label1.setText("Crédito");

        Destacado_checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destacado_checkBox1ActionPerformed(evt);
            }
        });

        Productos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Detalle", "Cantidad", "Descuento", "Precio Unidad", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(Productos_table);

        Agregar_button.setBackground(new java.awt.Color(136, 213, 133));
        Agregar_button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Agregar_button.setText("Agregar");
        Agregar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_buttonMouseClicked(evt);
            }
        });
        Agregar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_buttonActionPerformed(evt);
            }
        });

        Eliminar_button.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar_button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Eliminar_button.setText("Eliminar");

        Destacado_label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label2.setText("Efectivo");

        Efectivo_TextField.setBackground(new java.awt.Color(102, 255, 51));
        Efectivo_TextField.setToolTipText("Número de factura");
        Efectivo_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Efectivo_TextFieldActionPerformed(evt);
            }
        });

        Destacado_label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label3.setText("Cambio");

        Cambio_TextField.setForeground(new java.awt.Color(255, 51, 51));
        Cambio_TextField.setToolTipText("Número de factura");
        Cambio_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cambio_TextFieldActionPerformed(evt);
            }
        });

        Destacado_label4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label4.setText("Total");

        Total_TextField.setForeground(new java.awt.Color(255, 51, 51));
        Total_TextField.setToolTipText("Número de factura");
        Total_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TextFieldActionPerformed(evt);
            }
        });

        Guardar_Button.setText("Guardar");

        Limpiar_button.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezadoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(NoFactura_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Nombre_jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Nombre_TextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Apellido_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Apellido_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Direccion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Direccion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Direccion_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Destacado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Destacado_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(251, 251, 251))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Empleado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Empleado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Consumidor_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fecha_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NIT_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Destacado_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Destacado_checkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Direccion_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Detalles_TextField)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Guardar_Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(Limpiar_button))
                                    .addComponent(Agregar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Eliminar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Efectivo_TextField)
                                    .addComponent(Total_TextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cambio_TextField)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Destacado_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Destacado_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Destacado_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(encabezadoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Empleado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Consumidor_CheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Empleado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Fecha_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(NIT_CheckBox))
                                .addGap(5, 5, 5)
                                .addComponent(Destacado_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(Destacado_checkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoFactura_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Destacado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Destacado_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Direccion_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Direccion_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Detalles_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Agregar_button)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Destacado_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Efectivo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Destacado_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cambio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Destacado_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar_Button)
                    .addComponent(Limpiar_button))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        // TODO add your handling code here:
        Venta VentaWindow = new Venta(conexion, credenciales);
        VentaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_ButtonMouseClicked

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void Nombre_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_TextFieldActionPerformed

    private void NoFactura_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoFactura_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoFactura_TextField1ActionPerformed

    private void Apellido_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apellido_TextFieldActionPerformed

    private void Direccion_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Direccion_TextFieldActionPerformed

    private void Direccion_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Direccion_TextField1ActionPerformed

    private void Empleado_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empleado_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Empleado_TextFieldActionPerformed

    private void Fecha_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_TextFieldActionPerformed

    private void Destacado_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destacado_checkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Destacado_checkBoxActionPerformed

    private void Detalles_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detalles_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Detalles_TextFieldActionPerformed

    private void Destacado_checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destacado_checkBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Destacado_checkBox1ActionPerformed

    private void Agregar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_buttonMouseClicked
        
    }//GEN-LAST:event_Agregar_buttonMouseClicked

    private void Agregar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar_buttonActionPerformed

    private void Efectivo_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Efectivo_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Efectivo_TextFieldActionPerformed

    private void Cambio_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cambio_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cambio_TextFieldActionPerformed

    private void Total_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_button;
    private javax.swing.JButton Anular_button;
    private javax.swing.JButton Anular_button1;
    private javax.swing.JButton Anular_button2;
    private javax.swing.JLabel Apellido_Label;
    private javax.swing.JLabel Apellido_Label1;
    private javax.swing.JTextField Apellido_TextField;
    private javax.swing.JTextField Cambio_TextField;
    private javax.swing.JCheckBox Consumidor_CheckBox;
    private javax.swing.JCheckBox Destacado_checkBox;
    private javax.swing.JCheckBox Destacado_checkBox1;
    private javax.swing.JLabel Destacado_label;
    private javax.swing.JLabel Destacado_label1;
    private javax.swing.JLabel Destacado_label2;
    private javax.swing.JLabel Destacado_label3;
    private javax.swing.JLabel Destacado_label4;
    private javax.swing.JTextField Detalles_TextField;
    private javax.swing.JLabel Direccion_Label;
    private javax.swing.JLabel Direccion_Label1;
    private javax.swing.JTextField Direccion_TextField;
    private javax.swing.JTextField Direccion_TextField1;
    private javax.swing.JTextField Efectivo_TextField;
    private javax.swing.JButton Eliminar_button;
    private javax.swing.JTextField Empleado_TextField;
    private javax.swing.JLabel Empleado_label;
    private javax.swing.JTextField Fecha_TextField;
    private javax.swing.JLabel Fecha_label;
    private javax.swing.JButton Guardar_Button;
    private javax.swing.JButton Limpiar_button;
    private javax.swing.JCheckBox NIT_CheckBox;
    private javax.swing.JTextField NoFactura_TextField1;
    private javax.swing.JTextField Nombre_TextField;
    private javax.swing.JLabel Nombre_jLabel2;
    private javax.swing.JTable Productos_table;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JButton back_Button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel encabezadoJPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel puestoJLabel;
    // End of variables declaration//GEN-END:variables
}
