/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package corpoagrima.corpoagrima.gui.regventa;
import corpoagrima.corpoagrima.bdMariaDB.ConexionCliente;
import corpoagrima.corpoagrima.bdMariaDB.ConexionProducto;
import corpoagrima.corpoagrima.bdMariaDB.ConexionVenta;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 * @author Karol
 */
public class NuevoRegVenta extends javax.swing.JFrame {
    private final Connection conexion;
    private final ResultSet credenciales;
    private final ConexionCliente clientes;
    private final ConexionProducto producto;
    private final ConexionVenta venta;
    private int factura;
    /**
     * Creates new form EditarRegFactura
     * @param conexion
     * @param credenciales
     * @throws java.sql.SQLException
     */
    public NuevoRegVenta(Connection conexion, ResultSet credenciales) throws SQLException {
        this.conexion = conexion;
        this.credenciales = credenciales;
        this.venta = new ConexionVenta();
        producto = new ConexionProducto();
        clientes = new ConexionCliente();
        initComponents();
        datosTotales();
        
        Date fechaActual = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        String fechaTexto = formatoFecha.format(fechaActual);
        Fecha_TextField.setText(fechaTexto);
        
        String nombreEmpleado = credenciales.getString("Nombre");
        String apellidoEmpleado = credenciales.getString("Apellido");
        Empleado_TextField.setText(nombreEmpleado + " " + apellidoEmpleado);
        
        factura = obtenerUltimoNoFactura();
        NoFactura_TextField1.setText(String.valueOf(factura));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        encabezadoJPanel = new javax.swing.JPanel();
        puestoJLabel = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        Apellido_Label = new javax.swing.JLabel();
        Nombre_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NoFactura_TextField1 = new javax.swing.JTextField();
        Nombre_jLabel2 = new javax.swing.JLabel();
        Apellido_TextField = new javax.swing.JTextField();
        Apellido_Label1 = new javax.swing.JLabel();
        Direccion_TextField = new javax.swing.JTextField();
        Buscar_textField = new javax.swing.JTextField();
        Empleado_label = new javax.swing.JLabel();
        Empleado_TextField = new javax.swing.JTextField();
        Fecha_label = new javax.swing.JLabel();
        Fecha_TextField = new javax.swing.JTextField();
        Destacado_checkBox = new javax.swing.JCheckBox();
        Direccion_Label1 = new javax.swing.JLabel();
        Detalles_TextField = new javax.swing.JTextField();
        Consumidor_CheckBox = new javax.swing.JCheckBox();
        NIT_CheckBox = new javax.swing.JCheckBox();
        Credito_checkbox = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos_table = new javax.swing.JTable();
        Destacado_label2 = new javax.swing.JLabel();
        Efectivo_TextField = new javax.swing.JTextField();
        Destacado_label3 = new javax.swing.JLabel();
        Cambio_TextField = new javax.swing.JTextField();
        Buscar_Button = new javax.swing.JButton();
        totalProductoLabel = new javax.swing.JLabel();
        totalProductoJTextField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalJTextField = new javax.swing.JTextField();
        totalJTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Limpiar_button = new javax.swing.JButton();
        Guardar_button = new javax.swing.JButton();
        AgregarBn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EliminarBn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        encabezadoJPanel.setBackground(new java.awt.Color(34, 85, 34));

        puestoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        puestoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        puestoJLabel.setText("NUEVO REGISTRO DE VENTA");

        back_Button.setBackground(new java.awt.Color(34, 85, 34));
        back_Button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        back_Button.setForeground(new java.awt.Color(255, 255, 255));
        back_Button.setText("←");
        back_Button.setBorderPainted(false);
        back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout encabezadoJPanelLayout = new javax.swing.GroupLayout(encabezadoJPanel);
        encabezadoJPanel.setLayout(encabezadoJPanelLayout);
        encabezadoJPanelLayout.setHorizontalGroup(
            encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(back_Button)
                .addGap(199, 199, 199)
                .addComponent(puestoJLabel)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        encabezadoJPanelLayout.setVerticalGroup(
            encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, encabezadoJPanelLayout.createSequentialGroup()
                .addGroup(encabezadoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Apellido_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido_Label.setText("Apellido");

        Nombre_TextField.setEditable(false);
        Nombre_TextField.setToolTipText("Nombre del cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("No. Factura");

        NoFactura_TextField1.setEditable(false);
        NoFactura_TextField1.setToolTipText("Número de factura");

        Nombre_jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre_jLabel2.setText("Nombre");

        Apellido_TextField.setEditable(false);
        Apellido_TextField.setToolTipText("Apellido del cliente");

        Apellido_Label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido_Label1.setText("Dirección");

        Direccion_TextField.setEditable(false);
        Direccion_TextField.setToolTipText("Dirección del cliente");

        Buscar_textField.setEditable(false);
        Buscar_textField.setToolTipText("Búsqueda por NIT");

        Empleado_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Empleado_label.setText("Empleado");

        Empleado_TextField.setEditable(false);
        Empleado_TextField.setToolTipText("Empleado");

        Fecha_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fecha_label.setText("Fecha");

        Fecha_TextField.setEditable(false);
        Fecha_TextField.setToolTipText("Fecha");

        Destacado_checkBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_checkBox.setText("Destacado");
        Destacado_checkBox.setEnabled(false);

        Direccion_Label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Direccion_Label1.setText("Detalle");

        Detalles_TextField.setToolTipText("Detalle de factura");

        Consumidor_CheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Consumidor_CheckBox.setText("Consumidor Final");
        Consumidor_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Consumidor_CheckBoxItemStateChanged(evt);
            }
        });

        NIT_CheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIT_CheckBox.setText("NIT");
        NIT_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NIT_CheckBoxItemStateChanged(evt);
            }
        });

        Credito_checkbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Credito_checkbox.setText("Crédito");

        Productos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad", "Descuento", "Precio por Unidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Productos_table);

        Destacado_label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label2.setText("Efectivo");
        Destacado_label2.setToolTipText("");
        Destacado_label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Efectivo_TextField.setBackground(new java.awt.Color(102, 255, 51));
        Efectivo_TextField.setToolTipText("Cantidad de efectivo");

        Destacado_label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Destacado_label3.setText("Cambio");

        Cambio_TextField.setEditable(false);
        Cambio_TextField.setForeground(new java.awt.Color(255, 51, 51));
        Cambio_TextField.setToolTipText("Cambio ");

        Buscar_Button.setBackground(new java.awt.Color(136, 213, 133));
        Buscar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        Buscar_Button.setEnabled(false);
        Buscar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ButtonActionPerformed(evt);
            }
        });

        totalProductoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalProductoLabel.setText("Total de productos:");

        totalProductoJTextField.setEditable(false);
        totalProductoJTextField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(159, 46, 46));
        totalLabel.setText("Total");

        totalJTextField.setEditable(false);
        totalJTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        totalJTextField1.setEditable(false);
        totalJTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        Limpiar_button.setText("Limpiar");
        Limpiar_button.setEnabled(true);

        Guardar_button.setText("Guardar");
        Guardar_button.setEnabled(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(840, Short.MAX_VALUE)
                .addComponent(Guardar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Limpiar_button)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpiar_button)
                    .addComponent(Guardar_button)))
        );

        AgregarBn.setBackground(new java.awt.Color(136, 213, 133));
        AgregarBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N
        AgregarBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("AGREGAR");

        EliminarBn.setBackground(new java.awt.Color(136, 213, 133));
        EliminarBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminar.png"))); // NOI18N
        EliminarBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezadoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalProductoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(totalProductoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Destacado_label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(169, 169, 169))
                                    .addComponent(Destacado_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Efectivo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cambio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AgregarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EliminarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Apellido_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Apellido_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Detalles_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoFactura_TextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Direccion_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Destacado_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Fecha_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Empleado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Empleado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NIT_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Credito_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Consumidor_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Buscar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 494, Short.MAX_VALUE)
                    .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 494, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(encabezadoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fecha_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NoFactura_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NIT_CheckBox)
                                .addComponent(Buscar_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Buscar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Destacado_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Consumidor_CheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empleado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empleado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Credito_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apellido_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Detalles_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Destacado_label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Efectivo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Destacado_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cambio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalProductoLabel)
                        .addComponent(totalProductoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalLabel)
                    .addComponent(totalJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 375, Short.MAX_VALUE)
                    .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 375, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_ButtonMouseClicked
        // TODO add your handling code here:
        Venta VentaWindow = new Venta(conexion, credenciales);
        VentaWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_ButtonMouseClicked

     public void agregarProducto(int id) throws SQLException {
        ResultSet resultado = producto.busqueda2(conexion, id);

        // Obtener el modelo de la tabla actual
        DefaultTableModel model = (DefaultTableModel) Productos_table.getModel();

        resultado.next();
        String nombre = resultado.getString("Nombre");
        String descripcion = resultado.getString("Descripcion");
        String precio = resultado.getString("Precio_Venta");

        // Agregar a la tabla
        model.addRow(new Object[]{nombre, descripcion, 0, 0, precio, 0});
    }
     
    private void AgregarBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBnActionPerformed
        AgregarProductoRegFactura AgregarWindow = new AgregarProductoRegFactura(conexion, credenciales, this);
        AgregarWindow.setVisible(true);
    }//GEN-LAST:event_AgregarBnActionPerformed

    private void EliminarBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBnActionPerformed
        int fila = Productos_table.getSelectedRow();
        if (fila != -1) {
            DefaultTableModel model = (DefaultTableModel) Productos_table.getModel();
            model.removeRow(fila);
        }
    }//GEN-LAST:event_EliminarBnActionPerformed

    private void NIT_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NIT_CheckBoxItemStateChanged
        if (NIT_CheckBox.isSelected()) {
            Buscar_Button.setEnabled(true);
            Buscar_textField.setEditable(true);
        } else {
            Buscar_Button.setEnabled(false);
            Buscar_textField.setEditable(false);
            Nombre_TextField.setText("");
            Apellido_TextField.setText("");
            Direccion_TextField.setText("");
            Destacado_checkBox.setSelected(false);
        }
    }//GEN-LAST:event_NIT_CheckBoxItemStateChanged

    private void Buscar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ButtonActionPerformed
        String textoBusqueda = Buscar_textField.getText().trim();
        buscar(textoBusqueda);
    }//GEN-LAST:event_Buscar_ButtonActionPerformed

    private void Consumidor_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Consumidor_CheckBoxItemStateChanged
        if (Consumidor_CheckBox.isSelected()) {
            try {
                ResultSet rs = clientes.CF(conexion);
                if (rs.next()) {
                    String nombre = rs.getString("Nombre");
                    String apellido = rs.getString("Apellido");
                    String direccion = rs.getString("Direccion");

                    Nombre_TextField.setText(nombre);
                    Apellido_TextField.setText(apellido);
                    Direccion_TextField.setText(direccion);

                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(NuevoRegVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Nombre_TextField.setText("");
            Apellido_TextField.setText("");
            Direccion_TextField.setText("");
        }
    }//GEN-LAST:event_Consumidor_CheckBoxItemStateChanged

    
    public final void buscar(String textoBusqueda){
        try {
            if (textoBusqueda != null && !textoBusqueda.isEmpty()) {
                ResultSet rs = clientes.busqueda3(conexion, textoBusqueda);
                if (rs.next()) {
                    String nombre = rs.getString("Nombre");
                    String apellido = rs.getString("Apellido");
                    String direccion = rs.getString("Direccion");
                    int destacado = rs.getInt("Cliente_destacado");

                    if (destacado == 1) {
                        // Si el número es 1, marcamos el checkbox como seleccionado
                        Destacado_checkBox.setSelected(true);
                    } else {
                        // Si el número no es 1, no marcamos el checkbox
                        Destacado_checkBox.setSelected(false);
                    }

                    Nombre_TextField.setText(nombre);
                    Apellido_TextField.setText(apellido);
                    Direccion_TextField.setText(direccion);

                    JOptionPane.showMessageDialog(this, "La busqueda ha sido exitosa",
                            "Busqueda", JOptionPane.INFORMATION_MESSAGE);



                } else {
                    JOptionPane.showMessageDialog(this, "No se encontraron resultados",
                            "Busqueda", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR"
                        + "compruebe el codigo ingresado", "Busqueda",
                        JOptionPane.ERROR_MESSAGE);
            }

            } catch (SQLException ex) {
                Logger.getLogger(NuevoRegVenta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Ha habido un error "
                        + "compruebe la información", "Busqueda",
                        JOptionPane.ERROR_MESSAGE);
            }
    }
    private void datosTotales() {
        DefaultTableModel model = (DefaultTableModel) Productos_table.getModel();

        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE || e.getType() == TableModelEvent.INSERT || e.getType() == TableModelEvent.DELETE) {
                    int totalProductos = 0;
                    double total = 0;
                    int numFilas = model.getRowCount();
                    for (int fila = 0; fila < numFilas; fila++) {
                        totalProductos += Integer.parseInt(model.getValueAt(fila, 2).toString());
                        total += Double.parseDouble(model.getValueAt(fila, 5).toString());
                    }

                    totalProductoJTextField.setText(String.valueOf(totalProductos));
                    totalJTextField.setText(String.valueOf(total));
                }
            }
        });
    }
   public int obtenerUltimoNoFactura() throws SQLException {
       int ultimoNumeroFactura = 1;
        try (ResultSet resultNoFactura = venta.noFactura(conexion)) {
            if (resultNoFactura.next()) {
                ultimoNumeroFactura = resultNoFactura.getInt("maxFac");
                ultimoNumeroFactura += 1;
            }
        }
        return ultimoNumeroFactura;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBn;
    private javax.swing.JLabel Apellido_Label;
    private javax.swing.JLabel Apellido_Label1;
    private javax.swing.JTextField Apellido_TextField;
    private javax.swing.JButton Buscar_Button;
    private javax.swing.JTextField Buscar_textField;
    private javax.swing.JTextField Cambio_TextField;
    private javax.swing.JCheckBox Consumidor_CheckBox;
    private javax.swing.JCheckBox Credito_checkbox;
    private javax.swing.JCheckBox Destacado_checkBox;
    private javax.swing.JLabel Destacado_label2;
    private javax.swing.JLabel Destacado_label3;
    private javax.swing.JTextField Detalles_TextField;
    private javax.swing.JLabel Direccion_Label1;
    private javax.swing.JTextField Direccion_TextField;
    private javax.swing.JTextField Efectivo_TextField;
    private javax.swing.JButton EliminarBn;
    private javax.swing.JTextField Empleado_TextField;
    private javax.swing.JLabel Empleado_label;
    private javax.swing.JTextField Fecha_TextField;
    private javax.swing.JLabel Fecha_label;
    private javax.swing.JButton Guardar_button;
    private javax.swing.JButton Limpiar_button;
    private javax.swing.JCheckBox NIT_CheckBox;
    private javax.swing.JTextField NoFactura_TextField1;
    private javax.swing.JTextField Nombre_TextField;
    private javax.swing.JLabel Nombre_jLabel2;
    private javax.swing.JTable Productos_table;
    private javax.swing.JButton back_Button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel encabezadoJPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel puestoJLabel;
    private javax.swing.JTextField totalJTextField;
    private javax.swing.JTextField totalJTextField1;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalProductoJTextField;
    private javax.swing.JLabel totalProductoLabel;
    // End of variables declaration//GEN-END:variables
}
