package corpoagrima.corpoagrima.gui.regcompra;

import corpoagrima.corpoagrima.bdMariaDB.ConexionCompra;
import corpoagrima.corpoagrima.bdMariaDB.ConexionProducto;
import corpoagrima.corpoagrima.bdMariaDB.ConexionProveedores;
import corpoagrima.corpoagrima.bdMariaDB.ConexionRegCompraProducto;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 * @author WilderL
 */
public class NuevoRegFactura extends javax.swing.JFrame {

    private Connection conexion;
    private ResultSet credenciales;
    private ConexionCompra compra;
    private ConexionProducto producto;
    private ConexionProveedores proveedor;
    private ConexionRegCompraProducto compraProducto;
    private int idEmpleado;

    /**
     * Creates new form nuevoRegFactura
     */
    public NuevoRegFactura(Connection conexion, ResultSet credenciales) {
        try {
            this.conexion = conexion;
            this.idEmpleado = credenciales.getInt("ID_Empleado");
            this.credenciales = credenciales;
            producto = new ConexionProducto();
            initComponents();
            datosTotales();
            proveedor = new ConexionProveedores();
            compra = new ConexionCompra();
            compraProducto = new ConexionRegCompraProducto();
            ResultSet listaProveedor = proveedor.consulta(conexion);
            String nombreProveedor;
            while (listaProveedor.next()) {
                nombreProveedor = listaProveedor.getString("Empresa");
                Proveedor_comboBox.addItem(nombreProveedor);
            }
            String nombre = (String) Proveedor_comboBox.getSelectedItem();
            datoProveedor(nombre);
            String nombreEmpleado = credenciales.getString("Nombre");
            String apellidoEmpleado = credenciales.getString("Apellido");
            empleado_textfield.setText(nombreEmpleado + " " + apellidoEmpleado);

        } catch (SQLException ex) {
            Logger.getLogger(NuevoRegFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Regresar_Bn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        FechaLabel = new javax.swing.JLabel();
        FacturaLabel = new javax.swing.JLabel();
        fecha_textfield = new javax.swing.JTextField();
        telefono_textfield = new javax.swing.JTextField();
        CantidadComprasLabel = new javax.swing.JLabel();
        empleado_textfield = new javax.swing.JTextField();
        CorreoLabel = new javax.swing.JLabel();
        nit_textfield = new javax.swing.JTextField();
        DireccionLabel = new javax.swing.JLabel();
        ProveedorLabel = new javax.swing.JLabel();
        noFactura_textfield = new javax.swing.JTextField();
        credito_checkBox = new javax.swing.JCheckBox();
        Proveedor_comboBox = new javax.swing.JComboBox<>();
        detalle_textfield1 = new javax.swing.JTextField();
        CantidadComprasLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Limpiar_button = new javax.swing.JButton();
        Guardar_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EliminarBn = new javax.swing.JButton();
        AgregarBn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductoJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalProductoLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalJTextField = new javax.swing.JTextField();
        totalProductoJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 85, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVO REGISTRO FACTURA");

        Regresar_Bn.setBackground(new java.awt.Color(34, 85, 34));
        Regresar_Bn.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Regresar_Bn.setForeground(new java.awt.Color(255, 255, 255));
        Regresar_Bn.setText("←");
        Regresar_Bn.setBorderPainted(false);
        Regresar_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_BnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Regresar_Bn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Regresar_Bn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        FechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FechaLabel.setText("Fecha");

        FacturaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FacturaLabel.setText("No. Factura");

        fecha_textfield.setEditable(true);
        fecha_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        telefono_textfield.setEditable(false);
        telefono_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CantidadComprasLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CantidadComprasLabel.setText("Empleado");

        empleado_textfield.setEditable(false);
        empleado_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CorreoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CorreoLabel.setText("NIT");

        nit_textfield.setEditable(false);
        nit_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        DireccionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DireccionLabel.setText("Teléfono");

        ProveedorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProveedorLabel.setText("Proveedor");

        noFactura_textfield.setEditable(true
        );
        noFactura_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        credito_checkBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        credito_checkBox.setText("Credito");
        credito_checkBox.setEnabled(true);

        Proveedor_comboBox.setEnabled(true);
        Proveedor_comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Proveedor_comboBoxItemStateChanged(evt);
            }
        });

        detalle_textfield1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CantidadComprasLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CantidadComprasLabel2.setText("Detalle");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ProveedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FacturaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(noFactura_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DireccionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CantidadComprasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(empleado_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(telefono_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95)
                                .addComponent(CorreoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(credito_checkBox)
                                    .addComponent(nit_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CantidadComprasLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(detalle_textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Proveedor_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionLabel)
                            .addComponent(telefono_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantidadComprasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empleado_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacturaLabel)
                            .addComponent(CorreoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nit_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noFactura_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credito_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fecha_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(CantidadComprasLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProveedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Proveedor_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detalle_textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Limpiar_button.setText("Limpiar");
        Limpiar_button.setEnabled(true);
        Limpiar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_buttonActionPerformed(evt);
            }
        });

        Guardar_button.setText("Guardar");
        Guardar_button.setEnabled(true);
        Guardar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(941, Short.MAX_VALUE)
                .addComponent(Guardar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Limpiar_button)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpiar_button)
                    .addComponent(Guardar_button))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ELIMINAR");

        EliminarBn.setBackground(new java.awt.Color(136, 213, 133));
        EliminarBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminar.png"))); // NOI18N
        EliminarBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBnActionPerformed(evt);
            }
        });

        AgregarBn.setBackground(new java.awt.Color(136, 213, 133));
        AgregarBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N
        AgregarBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBnActionPerformed(evt);
            }
        });

        listaProductoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Marca", "Cantidad", "Costo por unidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaProductoJTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("AGREGAR");

        totalProductoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalProductoLabel.setText("Total de producto:");

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(159, 46, 46));
        totalLabel.setText("Total");

        totalJTextField.setEditable(false);
        totalJTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        totalProductoJTextField.setEditable(false);
        totalProductoJTextField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalProductoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalProductoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalLabel)
                                .addGap(18, 18, 18)
                                .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EliminarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarBn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalProductoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        noFactura_textfield.setText("");
        fecha_textfield.setText("");
        detalle_textfield1.setText("");
        credito_checkBox.setSelected(false);
        DefaultTableModel model = (DefaultTableModel) listaProductoJTable.getModel();
        model.setRowCount(0); // Elimina todas las filas
    }

    private void Regresar_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_BnActionPerformed
        // TODO add your handling code here:
        Compra compra_screen = new Compra(conexion, credenciales);
        compra_screen.setVisible(true);
        // Cerrar la ventana actual
        dispose();
    }//GEN-LAST:event_Regresar_BnActionPerformed

    private void Proveedor_comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Proveedor_comboBoxItemStateChanged
        Proveedor_comboBox.addItemListener((ItemEvent e) -> {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                try {
                    String nombre = (String) Proveedor_comboBox.getSelectedItem();
                    datoProveedor(nombre);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoRegFactura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_Proveedor_comboBoxItemStateChanged

    public void agregarProducto(int id) throws SQLException {
        ResultSet resultado = producto.busqueda2(conexion, id);

        // Obtener el modelo de la tabla actual
        DefaultTableModel model = (DefaultTableModel) listaProductoJTable.getModel();

        resultado.next();
        String nombre = resultado.getString("Nombre");
        String descripcion = resultado.getString("Descripcion");
        String marca = resultado.getString("Marca");

        // Agregar a la tabla
        model.addRow(new Object[]{nombre, descripcion, marca, 0, 0, 0, 0});
    }

    private void AgregarBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBnActionPerformed
        AgregarPRegFactura AgregarWindow = new AgregarPRegFactura(conexion, credenciales, this);
        AgregarWindow.setVisible(true);
    }//GEN-LAST:event_AgregarBnActionPerformed

    private void EliminarBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBnActionPerformed
        // TODO add your handling code here:
        int fila = listaProductoJTable.getSelectedRow();
        if (fila != -1) {
            DefaultTableModel model = (DefaultTableModel) listaProductoJTable.getModel();
            model.removeRow(fila);
        }
    }//GEN-LAST:event_EliminarBnActionPerformed

    private void Limpiar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_buttonActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_Limpiar_buttonActionPerformed

    private void Guardar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_buttonActionPerformed
        try {
            // datos del proveedor
            String nombreProveedor = (String) Proveedor_comboBox.getSelectedItem();
            ResultSet proveedorResultSet = this.proveedor.idProveedor(conexion, nombreProveedor);
            proveedorResultSet.next();
            int idProveedor = proveedorResultSet.getInt("ID_Proveedor");
            // datos de la factura
            String noFactura = noFactura_textfield.getText();
            String fecha = fecha_textfield.getText();
            boolean esCredito = credito_checkBox.isSelected();
            String credito = (esCredito) ? "Credito" : "Contado";
            float total = Float.parseFloat(totalJTextField.getText());
            // datos registro compra has producto
            String detalle = detalle_textfield1.getText();
            // guardado factura compra y obtener la id
            boolean compraResultSet = compra.agregar(conexion, noFactura, false,
                    fecha, credito, total, idProveedor, idEmpleado);
            if (compraResultSet) {
                throw new SQLException("Error al agregar un registro de compra");
            }
            ResultSet compraResult = compra.idCompra(conexion, noFactura);
            compraResult.next();
            int idCompra = compraResult.getInt("ID_Compra");
            // recolecion de datos de la tabla
            String nombreProducto;
            int cantidad;
            float costoUnidad;
            float costoTotal;
            DefaultTableModel modelo = (DefaultTableModel) listaProductoJTable.getModel();
            int numFilas = modelo.getRowCount();
            for (int fila = 0; fila < numFilas; fila++) {
                nombreProducto = modelo.getValueAt(fila, 0).toString();
                cantidad = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
                costoUnidad = Integer.parseInt(modelo.getValueAt(fila, 4).toString());
                costoTotal = Integer.parseInt(modelo.getValueAt(fila, 5).toString());

                // actualizar datos producto
                ResultSet productoResult = producto.cantidad(conexion, nombreProducto);
                int idProducto = productoResult.getInt("ID_Producto");
                int stock = productoResult.getInt("Stock");
                stock -= cantidad;
                producto.actualizar(conexion, idProducto, stock);
                // guardado registro compra has producto
                compraProducto.agregar(conexion, idCompra, idProducto, detalle,
                        cantidad, costoUnidad, costoTotal);
            }

            if (compraResultSet) {
                JOptionPane.showMessageDialog(this,
                        "Se ha guardado exitosamente.",
                        "Guardando", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NuevoRegFactura.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Se ha producido un error.",
                    "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Guardar_buttonActionPerformed

    private void datoProveedor(String nombre) throws SQLException {
        ResultSet proveedor = new ConexionProveedores().proveedor(conexion, nombre);
        proveedor.next();
        String numero = proveedor.getString("Numero");
        String nit = proveedor.getString("NIT");
        telefono_textfield.setText(numero);
        nit_textfield.setText(nit);
    }

    private void datosTotales() {
        DefaultTableModel model = (DefaultTableModel) listaProductoJTable.getModel();

        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE || e.getType() == TableModelEvent.INSERT || e.getType() == TableModelEvent.DELETE) {
                    int totalProductos = 0;
                    int total = 0;
                    int numFilas = model.getRowCount();
                    for (int fila = 0; fila < numFilas; fila++) {
                        totalProductos += Integer.parseInt(model.getValueAt(fila, 3).toString());
                        total += Integer.parseInt(model.getValueAt(fila, 5).toString());
                    }

                    totalProductoJTextField.setText(String.valueOf(totalProductos));
                    totalJTextField.setText(String.valueOf(total));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBn;
    private javax.swing.JLabel CantidadComprasLabel;
    private javax.swing.JLabel CantidadComprasLabel2;
    private javax.swing.JLabel CorreoLabel;
    private javax.swing.JLabel DireccionLabel;
    private javax.swing.JButton EliminarBn;
    private javax.swing.JLabel FacturaLabel;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JButton Guardar_button;
    private javax.swing.JButton Limpiar_button;
    private javax.swing.JLabel ProveedorLabel;
    private javax.swing.JComboBox<String> Proveedor_comboBox;
    private javax.swing.JButton Regresar_Bn;
    private javax.swing.JCheckBox credito_checkBox;
    private javax.swing.JTextField detalle_textfield1;
    private javax.swing.JTextField empleado_textfield;
    private javax.swing.JTextField fecha_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaProductoJTable;
    private javax.swing.JTextField nit_textfield;
    private javax.swing.JTextField noFactura_textfield;
    private javax.swing.JTextField telefono_textfield;
    private javax.swing.JTextField totalJTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalProductoJTextField;
    private javax.swing.JLabel totalProductoLabel;
    // End of variables declaration//GEN-END:variables
}
